### DATABASE ###
spring.datasource.url=jdbc:mysql://172.31.172.61:3306/foyer\
?createDatabaseIfNotExist=true\
&useUnicode=true\
&useJDBCCompliantTimezoneShift=true\
&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
server.port=8086
server.address=0.0.0.0

server.servlet.context-path=/Foyer
management.endpoints.web.exposure.include=prometheus,metrics,health
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true


### logging.file.name=/home/sirine-naifar/Documents/myinfo-%d{yyyy-MM-dd}.%i.log
### logging.logback.rollingpolicy.max-file-size= 10KB
