version: '3.8'

services:
  foyer-db:
    image: my-foyer-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foyer-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - foyer_db_data:/var/lib/mysql

  test-db:
    image: my-test-db
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: test-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - testdb_data:/var/lib/mysql

volumes:
  foyer_db_data:
  testdb_data:
