version: '3.8'

services:
  foyer-db:
    image: my-foyer-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foyer-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - foyer_db_data:/var/lib/mysql



volumes:
  foyer_db_data:
  testdb_data:
